In [1]:
import numpy as np


In [2]:
#creating 1-d array 
k=np.array([1,2,3,4,5])

In [3]:
print(k)

[1 2 3 4 5]


In [4]:
#creating 2-d array 
k1=np.array([[1,2,3],[3,4,5]])
print(k1)

[[1 2 3]
 [3 4 5]]


In [5]:
#creating 1-d array pf zeros 
k2=np.zeros((3))
print(k2)

[0. 0. 0.]


In [6]:
#creating 2-d array of zeros 
k3=np.zeros((2,3))
print(k3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#creating 1-d array of ones 
k4=np.ones(5)
print(k4)

[1. 1. 1. 1. 1.]


In [8]:
#creating 2-d array of ones
k5=np.zeros((2,3))
print(k5)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#demonstrating arithmetic operations 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[6,5,4],[3,2,1]])
#addition
print("addition of 2 arrays:\n",a+b)
print("subtraction of 2 arrays:\n",a-b)

addition of 2 arrays:
 [[7 7 7]
 [7 7 7]]
subtraction of 2 arrays:
 [[-5 -3 -1]
 [ 1  3  5]]


In [15]:
a=np.array([[1,3],[4,6]])
b=np.array([[5,6],[7,9]])
c=np.dot(a,b)
print("dot operation on 2-d arrays:",c);

dot operation on 1-d arrays: [[26 33]
 [62 78]]


In [16]:
a=np.array([[1,3],[4,6]])
b=np.array([[5,6],[7,9]])
c=a*b
print("general multiplication on 2-d arrays:",c);

general multiplication on 2-d arrays: [[ 5 18]
 [28 54]]
